//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relation
    {
        public int ID { get; set; }
        public Nullable<int> MasterID { get; set; }
        public Nullable<int> LessonID { get; set; }
    }
}
