//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLesson
    {
        public int ID { get; set; }
        public Nullable<int> Code { get; set; }
        public string Title { get; set; }
        public string Field { get; set; }
        public Nullable<int> UnitNum { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual tblMaster tblMaster { get; set; }
    }
}
